# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

post_install do |installer|
    # 需要指定编译版本的第三方的名称
    myTargets = ['ESPullToRefresh', 'GTMWebKit', 'ImageViewer', 'Alamofire', 'Toast-Swift', 'Cache']
    
    installer.pods_project.targets.each do |target|
        if myTargets.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4'
            end
        end
    end
end

target 'weiBo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for weiBo
    # Swift
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'HandyJSON'
    pod 'SnapKit'
    pod 'XCGLogger', :inhibit_warnings => true
    pod 'ImageViewer'
    pod 'GTMWebKit'
    pod 'ESPullToRefresh'
    pod 'Toast-Swift'
    pod 'Cache'
end
