# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'weiBo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for weiBo
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'YYModel'
    pod 'SDWebImage', '~> 3.8.2'
    pod 'SVProgressHUD'
    pod 'FMDB'
    
    # Swift
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'HandyJSON'
    pod 'SnapKit', '~> 3.2.0'
    pod 'XCGLogger', '~> 5.0.5'
end
